Models/ErrorViewModel.cs
namespace DSLW02Controllers.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MyDictionaryEntry.cs
namespace DSLW02Controllers.Models;

public class MyDictionaryEntry
{
    public string? Word { get; set; } = string.Empty;
    public string? Meaning { get; set; } = string.Empty;
}

Controllers/DictionaryController.cs
using DSLW02Controllers.Services;
using Microsoft.AspNetCore.Mvc;
using System.Web;

namespace DSLW02Controllers.Controllers;

public class DictionaryController : Controller
{
    private readonly IWordService _dictionary;

    public DictionaryController(IWordService dictionary)
    {
        _dictionary = dictionary;
    }

    public IActionResult Index()
    {
        return View(_dictionary.GetWords());
    }

    public IActionResult AddWord()
    {
        return View();
    }

    [HttpGet]
    public IActionResult AddNewWord(string word, string meaning)
    {
        word = HttpUtility.HtmlEncode(word);
        meaning = HttpUtility.HtmlEncode(meaning);
        _dictionary.AddWord(word, meaning);
        return RedirectToAction("Index");
    }
}

Controllers/HomeController.cs
using DSLW02Controllers.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Web;


namespace DSLW02Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult MyJson()
    {
        var obj = new MyDictionaryEntry() { Word = "Add", Meaning = "join (something) to something else so as to increase the size" };
        return Json(obj);
    }

    public IActionResult MyPdf()
    {
        return File("Lab 10.pdf", "application/pdf");
    }

    public IActionResult BarGraph(string? values)
    {
        values = HttpUtility.HtmlEncode(values);
        var model = values.Split("/");
        return View(model);
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Dictionary/AddWord.cshtml
@model DSLW02Controllers.Models.MyDictionaryEntry

@{
    ViewData["Title"] = "AddWord";
}

<h1>AddWord</h1>

<h4>MyDictionaryEntry</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddNewWord" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Word" class="control-label"></label>
                <input asp-for="Word" class="form-control" />
                <span asp-validation-for="Word" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Meaning" class="control-label"></label>
                <input asp-for="Meaning" class="form-control" />
                <span asp-validation-for="Meaning" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Dictionary/Index.cshtml
@model IEnumerable<DSLW02Controllers.Models.MyDictionaryEntry>

@{
    ViewData["Title"] = "The Words";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="AddWord">Add a New Word</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Word)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Meaning)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Word)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Meaning)
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Home/BarGraph.cshtml
@model string[]
@{
    ViewData["Title"] = "Bar Graph";
}

<h2>@ViewData["Title"]</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Item</td>
            <td>Graph</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var value in Model)
        {
            <tr>
                <td>
                    @value
                </td>
                <td>
                    @for (int i = 0; i < Int32.Parse(value.Substring(value.LastIndexOf('~') + 1)); i++)
                    {
                        @:&equiv;
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Lab Week 2 Controllers";
}

<div class="text-center">
    <h1 class="display-4">Lab Week 2 Controllers</h1>
    <p>Dylan Shaffer, Computing, Information Technology</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DSLW02Controllers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DSLW02Controllers.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DSLW02Controllers</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dictionary" asp-action="AddWord">Add Word</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dictionary" asp-action="Index">Index</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DSLW02Controllers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>